### ISSUE TITLE
👀 Looks like someone is using my api

### ISSUE THREAD

**Issue by PegasisForever** [teachassistapp/TeachAssist#1]
I probably should fix some bugs on my [server](https://github.com/PegasisForever/Fetch-TA-Data) and update my public api.

If you need more features from my api, feel free to open issues in my repo.

**Comment by york-wei** [comment]
![401](https://user-images.githubusercontent.com/49313072/168412463-d87f8c78-2802-4e49-a22e-6bc67f6b11f5.jpeg)

**Comment by npjd** [comment]
@PegasisForever lol yea, we spent a lot of work reversing the OCT website making an API for that and decided to use yours. We'd be down to collaborate to improve on the current one
