### ISSUE TITLE
Fix Dependancy issues

### ISSUE THREAD

**Issue by npjd** [teachassistapp/TeachAssist#2]
Get rid of node-fetch, I'm pretty sure we are using axios anyways

<img width="956" alt="image" src="https://user-images.githubusercontent.com/47256203/168665010-7ba22af3-5105-4e88-9242-04d5499acf8e.png">

**Comment by ryan-zhu-music** [comment]
This version of node-fetch is a dependency of the latest version of expo; until they update expo I'm not sure if we can fix it. See https://github.com/expo/expo-cli/issues/4230
